# configuration for https://travis-ci.org/bitcoinj/bitcoinj
sudo: false
language: java
jdk: oraclejdk8
install: true # remove default
script:
  - mvn -q clean -Prename-pom-version-like-branch
  - mvn deploy -Pno-network,release
  - jdk_switcher use openjdk6
  - cd orchid
  - mvn -q clean package
  - cd ../core
  - mvn -q clean package -Pno-network

after_success:
  - cd ../core
  - mvn jacoco:report coveralls:report

notifications:
  irc:
    channels: chat.freenode.net#bisq
    template:
      - '%{message} (%{repository}#%{build_number}, %{duration})'
      - '%{repository}/%{branch} %{commit} %{author}: %{commit_message}'
      - '%{build_url}'
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
