# configuration for https://travis-ci.org/bitcoinj/bitcoinj
sudo: false
language: java
jdk: oraclejdk8
install: true # remove default


# Login to travis if you have not yet $ travis login Now lets export our cert so we can encrypt it for travis.
#
# $ gpg --export --armor your@email.com > codesigning.asc
# $ gpg --export-secret-keys --armor your@email.com >> codesigning.asc
# Make sure your working directory is the git root of your project.
# Encrypt the keys $ travis encrypt-file codesigning.asc
# Take note of the line that looks like openssl aes-256-cbc -K...
# Shred the un-encrypted keys $ shred --remove codesigning.asc
# Make sure to move the created file to cd/codesigning.asc.enc

env:
  global:
    - secure: "the base64 string from when you encrypted OSSRH_JIRA_USERNAME"
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "the base64 string from when you encrypted OSSRH_JIRA_PASSWORD"
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "the base64 string from when you encrypted GPG_KEY_NAME"
    - # ^^ GPG_KEY_NAME
    - secure: "the base64 string from when you encrypted GPG_PASSPHRASE"
    - # ^^ GPG_PASSPHRASE

script:
  - mvn -q clean -Prename-pom-version-like-branch
  - mvn deploy -Pno-network,release
  - jdk_switcher use openjdk6
  - cd orchid
  - mvn -q clean package
  - cd ../core
  - mvn -q clean package -Pno-network

after_success:
  - cd ../core
  - mvn jacoco:report coveralls:report
  #  We want to be able to decrypt that file once we are on Travis CI, so we have a script to do that for us.
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh

notifications:
  irc:
    channels: chat.freenode.net#bisq
    template:
      - '%{message} (%{repository}#%{build_number}, %{duration})'
      - '%{repository}/%{branch} %{commit} %{author}: %{commit_message}'
      - '%{build_url}'
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
