// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storedclientpaymentchannel.proto

// Protobuf Java Version: 3.25.9
package org.bitcoinj.protocols.channels;

public final class ClientState {
  private ClientState() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StoredClientPaymentChannelsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:paymentchannels.StoredClientPaymentChannels)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    java.util.List<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel> 
        getChannelsList();
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel getChannels(int index);
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    int getChannelsCount();
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    java.util.List<? extends org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder> 
        getChannelsOrBuilderList();
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder getChannelsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * A set of StoredPaymentChannel's
   * </pre>
   *
   * Protobuf type {@code paymentchannels.StoredClientPaymentChannels}
   */
  public static final class StoredClientPaymentChannels extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:paymentchannels.StoredClientPaymentChannels)
      StoredClientPaymentChannelsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StoredClientPaymentChannels.newBuilder() to construct.
    private StoredClientPaymentChannels(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StoredClientPaymentChannels() {
      channels_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StoredClientPaymentChannels();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannels_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannels_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.class, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.Builder.class);
    }

    public static final int CHANNELS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel> channels_;
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    @Override
    public java.util.List<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel> getChannelsList() {
      return channels_;
    }
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    @Override
    public java.util.List<? extends org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder> 
        getChannelsOrBuilderList() {
      return channels_;
    }
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    @Override
    public int getChannelsCount() {
      return channels_.size();
    }
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    @Override
    public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel getChannels(int index) {
      return channels_.get(index);
    }
    /**
     * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
     */
    @Override
    public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder getChannelsOrBuilder(
        int index) {
      return channels_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getChannelsCount(); i++) {
        if (!getChannels(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < channels_.size(); i++) {
        output.writeMessage(1, channels_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < channels_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, channels_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels)) {
        return super.equals(obj);
      }
      org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels other = (org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels) obj;

      if (!getChannelsList()
          .equals(other.getChannelsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getChannelsCount() > 0) {
        hash = (37 * hash) + CHANNELS_FIELD_NUMBER;
        hash = (53 * hash) + getChannelsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A set of StoredPaymentChannel's
     * </pre>
     *
     * Protobuf type {@code paymentchannels.StoredClientPaymentChannels}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:paymentchannels.StoredClientPaymentChannels)
        org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannels_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannels_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.class, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.Builder.class);
      }

      // Construct using org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (channelsBuilder_ == null) {
          channels_ = java.util.Collections.emptyList();
        } else {
          channels_ = null;
          channelsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannels_descriptor;
      }

      @Override
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels getDefaultInstanceForType() {
        return org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.getDefaultInstance();
      }

      @Override
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels build() {
        org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels buildPartial() {
        org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels result = new org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels result) {
        if (channelsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            channels_ = java.util.Collections.unmodifiableList(channels_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.channels_ = channels_;
        } else {
          result.channels_ = channelsBuilder_.build();
        }
      }

      private void buildPartial0(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels result) {
        int from_bitField0_ = bitField0_;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels) {
          return mergeFrom((org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels other) {
        if (other == org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels.getDefaultInstance()) return this;
        if (channelsBuilder_ == null) {
          if (!other.channels_.isEmpty()) {
            if (channels_.isEmpty()) {
              channels_ = other.channels_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureChannelsIsMutable();
              channels_.addAll(other.channels_);
            }
            onChanged();
          }
        } else {
          if (!other.channels_.isEmpty()) {
            if (channelsBuilder_.isEmpty()) {
              channelsBuilder_.dispose();
              channelsBuilder_ = null;
              channels_ = other.channels_;
              bitField0_ = (bitField0_ & ~0x00000001);
              channelsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getChannelsFieldBuilder() : null;
            } else {
              channelsBuilder_.addAllMessages(other.channels_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        for (int i = 0; i < getChannelsCount(); i++) {
          if (!getChannels(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel m =
                    input.readMessage(
                        org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.PARSER,
                        extensionRegistry);
                if (channelsBuilder_ == null) {
                  ensureChannelsIsMutable();
                  channels_.add(m);
                } else {
                  channelsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel> channels_ =
        java.util.Collections.emptyList();
      private void ensureChannelsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          channels_ = new java.util.ArrayList<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel>(channels_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder> channelsBuilder_;

      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public java.util.List<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel> getChannelsList() {
        if (channelsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(channels_);
        } else {
          return channelsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public int getChannelsCount() {
        if (channelsBuilder_ == null) {
          return channels_.size();
        } else {
          return channelsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel getChannels(int index) {
        if (channelsBuilder_ == null) {
          return channels_.get(index);
        } else {
          return channelsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder setChannels(
          int index, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel value) {
        if (channelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChannelsIsMutable();
          channels_.set(index, value);
          onChanged();
        } else {
          channelsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder setChannels(
          int index, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder builderForValue) {
        if (channelsBuilder_ == null) {
          ensureChannelsIsMutable();
          channels_.set(index, builderForValue.build());
          onChanged();
        } else {
          channelsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel value) {
        if (channelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChannelsIsMutable();
          channels_.add(value);
          onChanged();
        } else {
          channelsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(
          int index, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel value) {
        if (channelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChannelsIsMutable();
          channels_.add(index, value);
          onChanged();
        } else {
          channelsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(
          org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder builderForValue) {
        if (channelsBuilder_ == null) {
          ensureChannelsIsMutable();
          channels_.add(builderForValue.build());
          onChanged();
        } else {
          channelsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(
          int index, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder builderForValue) {
        if (channelsBuilder_ == null) {
          ensureChannelsIsMutable();
          channels_.add(index, builderForValue.build());
          onChanged();
        } else {
          channelsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder addAllChannels(
          java.lang.Iterable<? extends org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel> values) {
        if (channelsBuilder_ == null) {
          ensureChannelsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, channels_);
          onChanged();
        } else {
          channelsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder clearChannels() {
        if (channelsBuilder_ == null) {
          channels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          channelsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public Builder removeChannels(int index) {
        if (channelsBuilder_ == null) {
          ensureChannelsIsMutable();
          channels_.remove(index);
          onChanged();
        } else {
          channelsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder getChannelsBuilder(
          int index) {
        return getChannelsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder getChannelsOrBuilder(
          int index) {
        if (channelsBuilder_ == null) {
          return channels_.get(index);  } else {
          return channelsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public java.util.List<? extends org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder> 
           getChannelsOrBuilderList() {
        if (channelsBuilder_ != null) {
          return channelsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(channels_);
        }
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder addChannelsBuilder() {
        return getChannelsFieldBuilder().addBuilder(
            org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.getDefaultInstance());
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder addChannelsBuilder(
          int index) {
        return getChannelsFieldBuilder().addBuilder(
            index, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.getDefaultInstance());
      }
      /**
       * <code>repeated .paymentchannels.StoredClientPaymentChannel channels = 1;</code>
       */
      public java.util.List<org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder> 
           getChannelsBuilderList() {
        return getChannelsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder> 
          getChannelsFieldBuilder() {
        if (channelsBuilder_ == null) {
          channelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder>(
                  channels_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          channels_ = null;
        }
        return channelsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:paymentchannels.StoredClientPaymentChannels)
    }

    // @@protoc_insertion_point(class_scope:paymentchannels.StoredClientPaymentChannels)
    private static final org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels();
    }

    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<StoredClientPaymentChannels>
        PARSER = new com.google.protobuf.AbstractParser<StoredClientPaymentChannels>() {
      @Override
      public StoredClientPaymentChannels parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StoredClientPaymentChannels> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<StoredClientPaymentChannels> getParserForType() {
      return PARSER;
    }

    @Override
    public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannels getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StoredClientPaymentChannelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:paymentchannels.StoredClientPaymentChannel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required bytes id = 1;</code>
     * @return The id.
     */
    com.google.protobuf.ByteString getId();

    /**
     * <code>required bytes contractTransaction = 2;</code>
     * @return Whether the contractTransaction field is set.
     */
    boolean hasContractTransaction();
    /**
     * <code>required bytes contractTransaction = 2;</code>
     * @return The contractTransaction.
     */
    com.google.protobuf.ByteString getContractTransaction();

    /**
     * <code>required bytes refundTransaction = 3;</code>
     * @return Whether the refundTransaction field is set.
     */
    boolean hasRefundTransaction();
    /**
     * <code>required bytes refundTransaction = 3;</code>
     * @return The refundTransaction.
     */
    com.google.protobuf.ByteString getRefundTransaction();

    /**
     * <code>required bytes myPublicKey = 8;</code>
     * @return Whether the myPublicKey field is set.
     */
    boolean hasMyPublicKey();
    /**
     * <code>required bytes myPublicKey = 8;</code>
     * @return The myPublicKey.
     */
    com.google.protobuf.ByteString getMyPublicKey();

    /**
     * <pre>
     * Deprecated, key is already stored in the wallet, and found using myPublicKey;
     * </pre>
     *
     * <code>required bytes myKey = 4;</code>
     * @return Whether the myKey field is set.
     */
    boolean hasMyKey();
    /**
     * <pre>
     * Deprecated, key is already stored in the wallet, and found using myPublicKey;
     * </pre>
     *
     * <code>required bytes myKey = 4;</code>
     * @return The myKey.
     */
    com.google.protobuf.ByteString getMyKey();

    /**
     * <code>required uint64 valueToMe = 5;</code>
     * @return Whether the valueToMe field is set.
     */
    boolean hasValueToMe();
    /**
     * <code>required uint64 valueToMe = 5;</code>
     * @return The valueToMe.
     */
    long getValueToMe();

    /**
     * <pre>
     * Fees required to refund the transaction.
     * </pre>
     *
     * <code>required uint64 refundFees = 6;</code>
     * @return Whether the refundFees field is set.
     */
    boolean hasRefundFees();
    /**
     * <pre>
     * Fees required to refund the transaction.
     * </pre>
     *
     * <code>required uint64 refundFees = 6;</code>
     * @return The refundFees.
     */
    long getRefundFees();

    /**
     * <pre>
     * When set, the hash of the transaction that was presented by the server for closure of the channel.
     * It spends the contractTransaction and is expected to be broadcast to the network by the server.
     * It's supposed to be in the wallet already.
     * </pre>
     *
     * <code>optional bytes closeTransactionHash = 7;</code>
     * @return Whether the closeTransactionHash field is set.
     */
    boolean hasCloseTransactionHash();
    /**
     * <pre>
     * When set, the hash of the transaction that was presented by the server for closure of the channel.
     * It spends the contractTransaction and is expected to be broadcast to the network by the server.
     * It's supposed to be in the wallet already.
     * </pre>
     *
     * <code>optional bytes closeTransactionHash = 7;</code>
     * @return The closeTransactionHash.
     */
    com.google.protobuf.ByteString getCloseTransactionHash();

    /**
     * <code>optional uint32 majorVersion = 9 [default = 1];</code>
     * @return Whether the majorVersion field is set.
     */
    boolean hasMajorVersion();
    /**
     * <code>optional uint32 majorVersion = 9 [default = 1];</code>
     * @return The majorVersion.
     */
    int getMajorVersion();

    /**
     * <pre>
     * The expiry time of the CLTV lock. Only used in protocol v2.
     * </pre>
     *
     * <code>optional uint64 expiryTime = 10;</code>
     * @return Whether the expiryTime field is set.
     */
    boolean hasExpiryTime();
    /**
     * <pre>
     * The expiry time of the CLTV lock. Only used in protocol v2.
     * </pre>
     *
     * <code>optional uint64 expiryTime = 10;</code>
     * @return The expiryTime.
     */
    long getExpiryTime();

    /**
     * <pre>
     * The server's public key. Only used in protocol v2.
     * </pre>
     *
     * <code>optional bytes serverKey = 11;</code>
     * @return Whether the serverKey field is set.
     */
    boolean hasServerKey();
    /**
     * <pre>
     * The server's public key. Only used in protocol v2.
     * </pre>
     *
     * <code>optional bytes serverKey = 11;</code>
     * @return The serverKey.
     */
    com.google.protobuf.ByteString getServerKey();
  }
  /**
   * <pre>
   * A client-side payment channel in serialized form, which can be reloaded later if the client restarts and wants to
   * reopen an existing channel
   * </pre>
   *
   * Protobuf type {@code paymentchannels.StoredClientPaymentChannel}
   */
  public static final class StoredClientPaymentChannel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:paymentchannels.StoredClientPaymentChannel)
      StoredClientPaymentChannelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StoredClientPaymentChannel.newBuilder() to construct.
    private StoredClientPaymentChannel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StoredClientPaymentChannel() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      contractTransaction_ = com.google.protobuf.ByteString.EMPTY;
      refundTransaction_ = com.google.protobuf.ByteString.EMPTY;
      myPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      myKey_ = com.google.protobuf.ByteString.EMPTY;
      closeTransactionHash_ = com.google.protobuf.ByteString.EMPTY;
      majorVersion_ = 1;
      serverKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StoredClientPaymentChannel();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannel_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.class, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes id = 1;</code>
     * @return Whether the id field is set.
     */
    @Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required bytes id = 1;</code>
     * @return The id.
     */
    @Override
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    public static final int CONTRACTTRANSACTION_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString contractTransaction_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes contractTransaction = 2;</code>
     * @return Whether the contractTransaction field is set.
     */
    @Override
    public boolean hasContractTransaction() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required bytes contractTransaction = 2;</code>
     * @return The contractTransaction.
     */
    @Override
    public com.google.protobuf.ByteString getContractTransaction() {
      return contractTransaction_;
    }

    public static final int REFUNDTRANSACTION_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString refundTransaction_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes refundTransaction = 3;</code>
     * @return Whether the refundTransaction field is set.
     */
    @Override
    public boolean hasRefundTransaction() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bytes refundTransaction = 3;</code>
     * @return The refundTransaction.
     */
    @Override
    public com.google.protobuf.ByteString getRefundTransaction() {
      return refundTransaction_;
    }

    public static final int MYPUBLICKEY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString myPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes myPublicKey = 8;</code>
     * @return Whether the myPublicKey field is set.
     */
    @Override
    public boolean hasMyPublicKey() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required bytes myPublicKey = 8;</code>
     * @return The myPublicKey.
     */
    @Override
    public com.google.protobuf.ByteString getMyPublicKey() {
      return myPublicKey_;
    }

    public static final int MYKEY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString myKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Deprecated, key is already stored in the wallet, and found using myPublicKey;
     * </pre>
     *
     * <code>required bytes myKey = 4;</code>
     * @return Whether the myKey field is set.
     */
    @Override
    public boolean hasMyKey() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Deprecated, key is already stored in the wallet, and found using myPublicKey;
     * </pre>
     *
     * <code>required bytes myKey = 4;</code>
     * @return The myKey.
     */
    @Override
    public com.google.protobuf.ByteString getMyKey() {
      return myKey_;
    }

    public static final int VALUETOME_FIELD_NUMBER = 5;
    private long valueToMe_ = 0L;
    /**
     * <code>required uint64 valueToMe = 5;</code>
     * @return Whether the valueToMe field is set.
     */
    @Override
    public boolean hasValueToMe() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required uint64 valueToMe = 5;</code>
     * @return The valueToMe.
     */
    @Override
    public long getValueToMe() {
      return valueToMe_;
    }

    public static final int REFUNDFEES_FIELD_NUMBER = 6;
    private long refundFees_ = 0L;
    /**
     * <pre>
     * Fees required to refund the transaction.
     * </pre>
     *
     * <code>required uint64 refundFees = 6;</code>
     * @return Whether the refundFees field is set.
     */
    @Override
    public boolean hasRefundFees() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * Fees required to refund the transaction.
     * </pre>
     *
     * <code>required uint64 refundFees = 6;</code>
     * @return The refundFees.
     */
    @Override
    public long getRefundFees() {
      return refundFees_;
    }

    public static final int CLOSETRANSACTIONHASH_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString closeTransactionHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * When set, the hash of the transaction that was presented by the server for closure of the channel.
     * It spends the contractTransaction and is expected to be broadcast to the network by the server.
     * It's supposed to be in the wallet already.
     * </pre>
     *
     * <code>optional bytes closeTransactionHash = 7;</code>
     * @return Whether the closeTransactionHash field is set.
     */
    @Override
    public boolean hasCloseTransactionHash() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * When set, the hash of the transaction that was presented by the server for closure of the channel.
     * It spends the contractTransaction and is expected to be broadcast to the network by the server.
     * It's supposed to be in the wallet already.
     * </pre>
     *
     * <code>optional bytes closeTransactionHash = 7;</code>
     * @return The closeTransactionHash.
     */
    @Override
    public com.google.protobuf.ByteString getCloseTransactionHash() {
      return closeTransactionHash_;
    }

    public static final int MAJORVERSION_FIELD_NUMBER = 9;
    private int majorVersion_ = 1;
    /**
     * <code>optional uint32 majorVersion = 9 [default = 1];</code>
     * @return Whether the majorVersion field is set.
     */
    @Override
    public boolean hasMajorVersion() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional uint32 majorVersion = 9 [default = 1];</code>
     * @return The majorVersion.
     */
    @Override
    public int getMajorVersion() {
      return majorVersion_;
    }

    public static final int EXPIRYTIME_FIELD_NUMBER = 10;
    private long expiryTime_ = 0L;
    /**
     * <pre>
     * The expiry time of the CLTV lock. Only used in protocol v2.
     * </pre>
     *
     * <code>optional uint64 expiryTime = 10;</code>
     * @return Whether the expiryTime field is set.
     */
    @Override
    public boolean hasExpiryTime() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     * The expiry time of the CLTV lock. Only used in protocol v2.
     * </pre>
     *
     * <code>optional uint64 expiryTime = 10;</code>
     * @return The expiryTime.
     */
    @Override
    public long getExpiryTime() {
      return expiryTime_;
    }

    public static final int SERVERKEY_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString serverKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The server's public key. Only used in protocol v2.
     * </pre>
     *
     * <code>optional bytes serverKey = 11;</code>
     * @return Whether the serverKey field is set.
     */
    @Override
    public boolean hasServerKey() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <pre>
     * The server's public key. Only used in protocol v2.
     * </pre>
     *
     * <code>optional bytes serverKey = 11;</code>
     * @return The serverKey.
     */
    @Override
    public com.google.protobuf.ByteString getServerKey() {
      return serverKey_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContractTransaction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRefundTransaction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMyPublicKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMyKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValueToMe()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRefundFees()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, contractTransaction_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(3, refundTransaction_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBytes(4, myKey_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeUInt64(5, valueToMe_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeUInt64(6, refundFees_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeBytes(7, closeTransactionHash_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(8, myPublicKey_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeUInt32(9, majorVersion_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeUInt64(10, expiryTime_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeBytes(11, serverKey_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, contractTransaction_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, refundTransaction_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, myKey_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, valueToMe_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, refundFees_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, closeTransactionHash_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, myPublicKey_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, majorVersion_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(10, expiryTime_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, serverKey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel)) {
        return super.equals(obj);
      }
      org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel other = (org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (!getId()
            .equals(other.getId())) return false;
      }
      if (hasContractTransaction() != other.hasContractTransaction()) return false;
      if (hasContractTransaction()) {
        if (!getContractTransaction()
            .equals(other.getContractTransaction())) return false;
      }
      if (hasRefundTransaction() != other.hasRefundTransaction()) return false;
      if (hasRefundTransaction()) {
        if (!getRefundTransaction()
            .equals(other.getRefundTransaction())) return false;
      }
      if (hasMyPublicKey() != other.hasMyPublicKey()) return false;
      if (hasMyPublicKey()) {
        if (!getMyPublicKey()
            .equals(other.getMyPublicKey())) return false;
      }
      if (hasMyKey() != other.hasMyKey()) return false;
      if (hasMyKey()) {
        if (!getMyKey()
            .equals(other.getMyKey())) return false;
      }
      if (hasValueToMe() != other.hasValueToMe()) return false;
      if (hasValueToMe()) {
        if (getValueToMe()
            != other.getValueToMe()) return false;
      }
      if (hasRefundFees() != other.hasRefundFees()) return false;
      if (hasRefundFees()) {
        if (getRefundFees()
            != other.getRefundFees()) return false;
      }
      if (hasCloseTransactionHash() != other.hasCloseTransactionHash()) return false;
      if (hasCloseTransactionHash()) {
        if (!getCloseTransactionHash()
            .equals(other.getCloseTransactionHash())) return false;
      }
      if (hasMajorVersion() != other.hasMajorVersion()) return false;
      if (hasMajorVersion()) {
        if (getMajorVersion()
            != other.getMajorVersion()) return false;
      }
      if (hasExpiryTime() != other.hasExpiryTime()) return false;
      if (hasExpiryTime()) {
        if (getExpiryTime()
            != other.getExpiryTime()) return false;
      }
      if (hasServerKey() != other.hasServerKey()) return false;
      if (hasServerKey()) {
        if (!getServerKey()
            .equals(other.getServerKey())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasContractTransaction()) {
        hash = (37 * hash) + CONTRACTTRANSACTION_FIELD_NUMBER;
        hash = (53 * hash) + getContractTransaction().hashCode();
      }
      if (hasRefundTransaction()) {
        hash = (37 * hash) + REFUNDTRANSACTION_FIELD_NUMBER;
        hash = (53 * hash) + getRefundTransaction().hashCode();
      }
      if (hasMyPublicKey()) {
        hash = (37 * hash) + MYPUBLICKEY_FIELD_NUMBER;
        hash = (53 * hash) + getMyPublicKey().hashCode();
      }
      if (hasMyKey()) {
        hash = (37 * hash) + MYKEY_FIELD_NUMBER;
        hash = (53 * hash) + getMyKey().hashCode();
      }
      if (hasValueToMe()) {
        hash = (37 * hash) + VALUETOME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getValueToMe());
      }
      if (hasRefundFees()) {
        hash = (37 * hash) + REFUNDFEES_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRefundFees());
      }
      if (hasCloseTransactionHash()) {
        hash = (37 * hash) + CLOSETRANSACTIONHASH_FIELD_NUMBER;
        hash = (53 * hash) + getCloseTransactionHash().hashCode();
      }
      if (hasMajorVersion()) {
        hash = (37 * hash) + MAJORVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getMajorVersion();
      }
      if (hasExpiryTime()) {
        hash = (37 * hash) + EXPIRYTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getExpiryTime());
      }
      if (hasServerKey()) {
        hash = (37 * hash) + SERVERKEY_FIELD_NUMBER;
        hash = (53 * hash) + getServerKey().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A client-side payment channel in serialized form, which can be reloaded later if the client restarts and wants to
     * reopen an existing channel
     * </pre>
     *
     * Protobuf type {@code paymentchannels.StoredClientPaymentChannel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:paymentchannels.StoredClientPaymentChannel)
        org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannel_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.class, org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.Builder.class);
      }

      // Construct using org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = com.google.protobuf.ByteString.EMPTY;
        contractTransaction_ = com.google.protobuf.ByteString.EMPTY;
        refundTransaction_ = com.google.protobuf.ByteString.EMPTY;
        myPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        myKey_ = com.google.protobuf.ByteString.EMPTY;
        valueToMe_ = 0L;
        refundFees_ = 0L;
        closeTransactionHash_ = com.google.protobuf.ByteString.EMPTY;
        majorVersion_ = 1;
        expiryTime_ = 0L;
        serverKey_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoinj.protocols.channels.ClientState.internal_static_paymentchannels_StoredClientPaymentChannel_descriptor;
      }

      @Override
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel getDefaultInstanceForType() {
        return org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.getDefaultInstance();
      }

      @Override
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel build() {
        org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel buildPartial() {
        org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel result = new org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.contractTransaction_ = contractTransaction_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.refundTransaction_ = refundTransaction_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.myPublicKey_ = myPublicKey_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.myKey_ = myKey_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.valueToMe_ = valueToMe_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.refundFees_ = refundFees_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.closeTransactionHash_ = closeTransactionHash_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.majorVersion_ = majorVersion_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.expiryTime_ = expiryTime_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.serverKey_ = serverKey_;
          to_bitField0_ |= 0x00000400;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel) {
          return mergeFrom((org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel other) {
        if (other == org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasContractTransaction()) {
          setContractTransaction(other.getContractTransaction());
        }
        if (other.hasRefundTransaction()) {
          setRefundTransaction(other.getRefundTransaction());
        }
        if (other.hasMyPublicKey()) {
          setMyPublicKey(other.getMyPublicKey());
        }
        if (other.hasMyKey()) {
          setMyKey(other.getMyKey());
        }
        if (other.hasValueToMe()) {
          setValueToMe(other.getValueToMe());
        }
        if (other.hasRefundFees()) {
          setRefundFees(other.getRefundFees());
        }
        if (other.hasCloseTransactionHash()) {
          setCloseTransactionHash(other.getCloseTransactionHash());
        }
        if (other.hasMajorVersion()) {
          setMajorVersion(other.getMajorVersion());
        }
        if (other.hasExpiryTime()) {
          setExpiryTime(other.getExpiryTime());
        }
        if (other.hasServerKey()) {
          setServerKey(other.getServerKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasContractTransaction()) {
          return false;
        }
        if (!hasRefundTransaction()) {
          return false;
        }
        if (!hasMyPublicKey()) {
          return false;
        }
        if (!hasMyKey()) {
          return false;
        }
        if (!hasValueToMe()) {
          return false;
        }
        if (!hasRefundFees()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                contractTransaction_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                refundTransaction_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                myKey_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 34
              case 40: {
                valueToMe_ = input.readUInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 40
              case 48: {
                refundFees_ = input.readUInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 48
              case 58: {
                closeTransactionHash_ = input.readBytes();
                bitField0_ |= 0x00000080;
                break;
              } // case 58
              case 66: {
                myPublicKey_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 66
              case 72: {
                majorVersion_ = input.readUInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 80: {
                expiryTime_ = input.readUInt64();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              case 90: {
                serverKey_ = input.readBytes();
                bitField0_ |= 0x00000400;
                break;
              } // case 90
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes id = 1;</code>
       * @return Whether the id field is set.
       */
      @Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required bytes id = 1;</code>
       * @return The id.
       */
      @Override
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>required bytes id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString contractTransaction_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes contractTransaction = 2;</code>
       * @return Whether the contractTransaction field is set.
       */
      @Override
      public boolean hasContractTransaction() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required bytes contractTransaction = 2;</code>
       * @return The contractTransaction.
       */
      @Override
      public com.google.protobuf.ByteString getContractTransaction() {
        return contractTransaction_;
      }
      /**
       * <code>required bytes contractTransaction = 2;</code>
       * @param value The contractTransaction to set.
       * @return This builder for chaining.
       */
      public Builder setContractTransaction(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        contractTransaction_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes contractTransaction = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContractTransaction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        contractTransaction_ = getDefaultInstance().getContractTransaction();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString refundTransaction_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes refundTransaction = 3;</code>
       * @return Whether the refundTransaction field is set.
       */
      @Override
      public boolean hasRefundTransaction() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required bytes refundTransaction = 3;</code>
       * @return The refundTransaction.
       */
      @Override
      public com.google.protobuf.ByteString getRefundTransaction() {
        return refundTransaction_;
      }
      /**
       * <code>required bytes refundTransaction = 3;</code>
       * @param value The refundTransaction to set.
       * @return This builder for chaining.
       */
      public Builder setRefundTransaction(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        refundTransaction_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes refundTransaction = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRefundTransaction() {
        bitField0_ = (bitField0_ & ~0x00000004);
        refundTransaction_ = getDefaultInstance().getRefundTransaction();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString myPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes myPublicKey = 8;</code>
       * @return Whether the myPublicKey field is set.
       */
      @Override
      public boolean hasMyPublicKey() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required bytes myPublicKey = 8;</code>
       * @return The myPublicKey.
       */
      @Override
      public com.google.protobuf.ByteString getMyPublicKey() {
        return myPublicKey_;
      }
      /**
       * <code>required bytes myPublicKey = 8;</code>
       * @param value The myPublicKey to set.
       * @return This builder for chaining.
       */
      public Builder setMyPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        myPublicKey_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes myPublicKey = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMyPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        myPublicKey_ = getDefaultInstance().getMyPublicKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString myKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Deprecated, key is already stored in the wallet, and found using myPublicKey;
       * </pre>
       *
       * <code>required bytes myKey = 4;</code>
       * @return Whether the myKey field is set.
       */
      @Override
      public boolean hasMyKey() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * Deprecated, key is already stored in the wallet, and found using myPublicKey;
       * </pre>
       *
       * <code>required bytes myKey = 4;</code>
       * @return The myKey.
       */
      @Override
      public com.google.protobuf.ByteString getMyKey() {
        return myKey_;
      }
      /**
       * <pre>
       * Deprecated, key is already stored in the wallet, and found using myPublicKey;
       * </pre>
       *
       * <code>required bytes myKey = 4;</code>
       * @param value The myKey to set.
       * @return This builder for chaining.
       */
      public Builder setMyKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        myKey_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Deprecated, key is already stored in the wallet, and found using myPublicKey;
       * </pre>
       *
       * <code>required bytes myKey = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMyKey() {
        bitField0_ = (bitField0_ & ~0x00000010);
        myKey_ = getDefaultInstance().getMyKey();
        onChanged();
        return this;
      }

      private long valueToMe_ ;
      /**
       * <code>required uint64 valueToMe = 5;</code>
       * @return Whether the valueToMe field is set.
       */
      @Override
      public boolean hasValueToMe() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required uint64 valueToMe = 5;</code>
       * @return The valueToMe.
       */
      @Override
      public long getValueToMe() {
        return valueToMe_;
      }
      /**
       * <code>required uint64 valueToMe = 5;</code>
       * @param value The valueToMe to set.
       * @return This builder for chaining.
       */
      public Builder setValueToMe(long value) {

        valueToMe_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 valueToMe = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearValueToMe() {
        bitField0_ = (bitField0_ & ~0x00000020);
        valueToMe_ = 0L;
        onChanged();
        return this;
      }

      private long refundFees_ ;
      /**
       * <pre>
       * Fees required to refund the transaction.
       * </pre>
       *
       * <code>required uint64 refundFees = 6;</code>
       * @return Whether the refundFees field is set.
       */
      @Override
      public boolean hasRefundFees() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       * Fees required to refund the transaction.
       * </pre>
       *
       * <code>required uint64 refundFees = 6;</code>
       * @return The refundFees.
       */
      @Override
      public long getRefundFees() {
        return refundFees_;
      }
      /**
       * <pre>
       * Fees required to refund the transaction.
       * </pre>
       *
       * <code>required uint64 refundFees = 6;</code>
       * @param value The refundFees to set.
       * @return This builder for chaining.
       */
      public Builder setRefundFees(long value) {

        refundFees_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Fees required to refund the transaction.
       * </pre>
       *
       * <code>required uint64 refundFees = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRefundFees() {
        bitField0_ = (bitField0_ & ~0x00000040);
        refundFees_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString closeTransactionHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * When set, the hash of the transaction that was presented by the server for closure of the channel.
       * It spends the contractTransaction and is expected to be broadcast to the network by the server.
       * It's supposed to be in the wallet already.
       * </pre>
       *
       * <code>optional bytes closeTransactionHash = 7;</code>
       * @return Whether the closeTransactionHash field is set.
       */
      @Override
      public boolean hasCloseTransactionHash() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       * When set, the hash of the transaction that was presented by the server for closure of the channel.
       * It spends the contractTransaction and is expected to be broadcast to the network by the server.
       * It's supposed to be in the wallet already.
       * </pre>
       *
       * <code>optional bytes closeTransactionHash = 7;</code>
       * @return The closeTransactionHash.
       */
      @Override
      public com.google.protobuf.ByteString getCloseTransactionHash() {
        return closeTransactionHash_;
      }
      /**
       * <pre>
       * When set, the hash of the transaction that was presented by the server for closure of the channel.
       * It spends the contractTransaction and is expected to be broadcast to the network by the server.
       * It's supposed to be in the wallet already.
       * </pre>
       *
       * <code>optional bytes closeTransactionHash = 7;</code>
       * @param value The closeTransactionHash to set.
       * @return This builder for chaining.
       */
      public Builder setCloseTransactionHash(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        closeTransactionHash_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * When set, the hash of the transaction that was presented by the server for closure of the channel.
       * It spends the contractTransaction and is expected to be broadcast to the network by the server.
       * It's supposed to be in the wallet already.
       * </pre>
       *
       * <code>optional bytes closeTransactionHash = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCloseTransactionHash() {
        bitField0_ = (bitField0_ & ~0x00000080);
        closeTransactionHash_ = getDefaultInstance().getCloseTransactionHash();
        onChanged();
        return this;
      }

      private int majorVersion_ = 1;
      /**
       * <code>optional uint32 majorVersion = 9 [default = 1];</code>
       * @return Whether the majorVersion field is set.
       */
      @Override
      public boolean hasMajorVersion() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional uint32 majorVersion = 9 [default = 1];</code>
       * @return The majorVersion.
       */
      @Override
      public int getMajorVersion() {
        return majorVersion_;
      }
      /**
       * <code>optional uint32 majorVersion = 9 [default = 1];</code>
       * @param value The majorVersion to set.
       * @return This builder for chaining.
       */
      public Builder setMajorVersion(int value) {

        majorVersion_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 majorVersion = 9 [default = 1];</code>
       * @return This builder for chaining.
       */
      public Builder clearMajorVersion() {
        bitField0_ = (bitField0_ & ~0x00000100);
        majorVersion_ = 1;
        onChanged();
        return this;
      }

      private long expiryTime_ ;
      /**
       * <pre>
       * The expiry time of the CLTV lock. Only used in protocol v2.
       * </pre>
       *
       * <code>optional uint64 expiryTime = 10;</code>
       * @return Whether the expiryTime field is set.
       */
      @Override
      public boolean hasExpiryTime() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <pre>
       * The expiry time of the CLTV lock. Only used in protocol v2.
       * </pre>
       *
       * <code>optional uint64 expiryTime = 10;</code>
       * @return The expiryTime.
       */
      @Override
      public long getExpiryTime() {
        return expiryTime_;
      }
      /**
       * <pre>
       * The expiry time of the CLTV lock. Only used in protocol v2.
       * </pre>
       *
       * <code>optional uint64 expiryTime = 10;</code>
       * @param value The expiryTime to set.
       * @return This builder for chaining.
       */
      public Builder setExpiryTime(long value) {

        expiryTime_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The expiry time of the CLTV lock. Only used in protocol v2.
       * </pre>
       *
       * <code>optional uint64 expiryTime = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpiryTime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        expiryTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString serverKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The server's public key. Only used in protocol v2.
       * </pre>
       *
       * <code>optional bytes serverKey = 11;</code>
       * @return Whether the serverKey field is set.
       */
      @Override
      public boolean hasServerKey() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <pre>
       * The server's public key. Only used in protocol v2.
       * </pre>
       *
       * <code>optional bytes serverKey = 11;</code>
       * @return The serverKey.
       */
      @Override
      public com.google.protobuf.ByteString getServerKey() {
        return serverKey_;
      }
      /**
       * <pre>
       * The server's public key. Only used in protocol v2.
       * </pre>
       *
       * <code>optional bytes serverKey = 11;</code>
       * @param value The serverKey to set.
       * @return This builder for chaining.
       */
      public Builder setServerKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        serverKey_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The server's public key. Only used in protocol v2.
       * </pre>
       *
       * <code>optional bytes serverKey = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerKey() {
        bitField0_ = (bitField0_ & ~0x00000400);
        serverKey_ = getDefaultInstance().getServerKey();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:paymentchannels.StoredClientPaymentChannel)
    }

    // @@protoc_insertion_point(class_scope:paymentchannels.StoredClientPaymentChannel)
    private static final org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel();
    }

    public static org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<StoredClientPaymentChannel>
        PARSER = new com.google.protobuf.AbstractParser<StoredClientPaymentChannel>() {
      @Override
      public StoredClientPaymentChannel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StoredClientPaymentChannel> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<StoredClientPaymentChannel> getParserForType() {
      return PARSER;
    }

    @Override
    public org.bitcoinj.protocols.channels.ClientState.StoredClientPaymentChannel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentchannels_StoredClientPaymentChannels_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paymentchannels_StoredClientPaymentChannels_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentchannels_StoredClientPaymentChannel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paymentchannels_StoredClientPaymentChannel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n storedclientpaymentchannel.proto\022\017paym" +
      "entchannels\"\\\n\033StoredClientPaymentChanne" +
      "ls\022=\n\010channels\030\001 \003(\0132+.paymentchannels.S" +
      "toredClientPaymentChannel\"\211\002\n\032StoredClie" +
      "ntPaymentChannel\022\n\n\002id\030\001 \002(\014\022\033\n\023contract" +
      "Transaction\030\002 \002(\014\022\031\n\021refundTransaction\030\003" +
      " \002(\014\022\023\n\013myPublicKey\030\010 \002(\014\022\r\n\005myKey\030\004 \002(\014" +
      "\022\021\n\tvalueToMe\030\005 \002(\004\022\022\n\nrefundFees\030\006 \002(\004\022" +
      "\034\n\024closeTransactionHash\030\007 \001(\014\022\027\n\014majorVe" +
      "rsion\030\t \001(\r:\0011\022\022\n\nexpiryTime\030\n \001(\004\022\021\n\tse" +
      "rverKey\030\013 \001(\014B.\n\037org.bitcoinj.protocols." +
      "channelsB\013ClientState"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_paymentchannels_StoredClientPaymentChannels_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_paymentchannels_StoredClientPaymentChannels_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paymentchannels_StoredClientPaymentChannels_descriptor,
        new java.lang.String[] { "Channels", });
    internal_static_paymentchannels_StoredClientPaymentChannel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_paymentchannels_StoredClientPaymentChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paymentchannels_StoredClientPaymentChannel_descriptor,
        new java.lang.String[] { "Id", "ContractTransaction", "RefundTransaction", "MyPublicKey", "MyKey", "ValueToMe", "RefundFees", "CloseTransactionHash", "MajorVersion", "ExpiryTime", "ServerKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
